const EnglishKeys = {
        '진로관 1층 계단': 'The stairs on the 1st floor of the Jinro building',
        '진로관 1층 중앙': 'The center of the 1st floor of Jinro Building',
        '1층통로': 'a first-floor passageway',
        '시청각실': 'AV room',
        '교과교실2': 'Curriculum Classroom 2',
        '교과교실1': 'Curriculum Classroom 1',
        '진로관 1층 화장실': 'restroom on the 1st floor of Jinro Building',
        '진로관 2층 중앙': 'The center of the 2nd floor of Jinro Building',
        '진로관 2층 계단': 'The stairs on the 2nd floor of the Jinro building',
        '진로관 2층 화장실': 'restroom on the 2nd floor of Jinro Building',
        '3-2': '3-2',
        '3-3': '3-3',
        '3-1': '3-1',
        '3학년 교무실': "Teachers' Office for 3rd Graders",
        '2층통로': 'a two-story passageway',
        '진로관 3층 계단': 'The stairs on the 3rd floor of the Jinro building',
        '진로관 3층 중앙': 'The center of the 3rd floor of Jinro Building',
        '진로관 3층 화장실': 'restroom on the 3rd floor of Jinro Building',
        '3-7': '3-7',
        '3-8': '3-8',
        '3-6': '3-6',
        '3-5': '3-5',
        '3-4': '3-4',
        '교과교실3': 'Curriculum Classroom 3',
        '3층통로': 'a third-floor passageway',
        '과학교실3': 'a science Classroom 3',
        '공동교육과정 온라인교실': 'an online classroom in a joint curriculum',
        '창학관 1층 중앙': 'The center of the 1st floor of Changhak building',
        '창학관 1층 화장실': 'The restroom on the 1st floor of Changhak building',
        '다락': 'Darak',
        '창학관 1층 계단': 'The stairs on the 1st floor of the Changhak building',
        '창학관 1층 현관': 'The entrance to the 1st floor of Changhak Building',
        '생물실': 'a living room',
        
        '창학관 2층 계단': 'The stairs on the 2nd floor of the Changhak building',
        '창학관 2층 중앙': 'The center of the 2nd floor of Changhak building',
        '창의융합실': 'a creative fusion room',
        '지구과학실': 'Earth Science room',
        '창학관 2층 화장실': 'The restroom on the 2nd floor of Changhak building',
        '컴퓨터실': 'Computer Lab',
        '과학 동아리실': 'Science club room',
        '융합교육부': 'Ministry of Convergence Education',
        
        '창학관 3층 계단': 'The stairs on the 3rd floor of the Changhak building',
        '창학관 3층 중앙': 'The center of the 3rd floor of Changhak building',
        '창학관 3층 화장실': 'The restroom on the 3rd floor of Changhak building',
        '연구실': 'a laboratory',
        '멀티미디어실': 'Multimedia room',
        '화학실': 'a chemistry room',
        'Wee class': 'Wee class',
        '프로파일실': 'Profile room',
        
        '통로': 'passageway',
        
        '본관 2층 우측 계단': 'the stairs to the right on the 2nd floor of the main building',
        '본관 2층 우측 화장실': 'the restroom on the right side of the 2nd floor of the main building',
        '보건실': 'Health Room',
        '교육정보실': 'Education Information Office',
        '학생생활안전교육부': 'Ministry of Student Life Safety and Education',
        '본관 2층 중앙':'the center on the 2nd floor of the main building',
        '본관 2층 중앙 계단': 'the center stairs on the 2nd floor of the main building',
        '방송실': 'Broadcasting room',
        '교무실': "Teachers' Office",
        '2층 원형 계단': 'The circular staircase on the 2nd floor',
        '교장실': "principal's Office",
        '창의인재부': 'the Ministry of Creative Resources',
        '본관 2층 좌측 화장실': 'the restroom on the left side of the 2nd floor of the main building',
        '본관 2층 좌측 계단': 'the stairs to the left on the 2nd floor of the main building',
        
        '본관 1층 우측 계단': 'the stairs to the right on the 1st floor of the main building',
        '보일러실': 'a boiler room',
        '발간실': 'a publishing room',
        '행정실': 'administrative office',
        '본관 1층 중앙': 'The center of the 1st floor of the main building',
        '1층 원형 계단': 'The circular staircase on the 1st floor',
        '문서고': 'an archive',
        '학습도움실2': 'Learning Help Room 2',
        '학습도움실1': 'Learning Help Room 1',
        '본관 1층 화장실': 'the restroom of the 1st floor of the main building',
        '본관 1층 좌측 계단': 'the stairs to the left on the 1st floor of the main building',
        
        '본관 3층 우측 계단': 'the stairs to the right on the 3rd floor of the main building',
        '본관 3층 우측 화장실': 'the restroom on the right side of the 3rd floor of the main building',
        '1-8': '1-8',
        '1-7': '1-7',
        '1-6': '1-6',
        '1-5': '1-5',
        '3층 홈베이스': 'the home base on the 3rd floor',
        '본관 3층 중앙 계단': 'the center stairs on the 3rd floor of the main building',
        '1학년 교무실': "Teachers' Office for 1st Graders",
        '1-4': '1-4',
        '1-3': '1-3',
        '1-2': '1-2',
        '1-1': '1-1',
        '본관 3층 좌측 계단': 'the stairs to the left on the 3rd floor of the main building',
        '본관 3층 좌측 화장실': 'the restroom on the left side of the 3rd floor of the main building',
        
        '본관 4층 우측 계단': 'the stairs to the right on the 4th floor of the main building',
        '본관 4층 우측 화장실': 'the restroom on the right side of the 4th floor of the main building',
        '2-8': '2-8',
        '2-7': '2-7',
        '2-6': '2-6',
        '2-5': '2-5',
        '4층 홈베이스': 'the home base on the 4th floor',
        '본관 4층 중앙 계단': 'the center stairs on the 4th floor of the main building',
        '2학년 교무실': "Teachers' Office for 2nd Graders",
        '2-4': '2-4',
        '2-3': '2-3',
        '2-2': '2-2',
        '2-1': '2-1',
        '본관 4층 좌측 계단': 'the stairs to the left on the 4th floor of the main building',
        '본관 4층 좌측 화장실': 'the restroom on the left side of the 4th floor of the main building',
        '후관 입구':'the entrance to the rear building',
        '후관 2층 계단':'the 2nd floor of the rear building',
        '미술실':'art room',
        '후관 3층 좌측 계단':'the left staircase on the 3rd floor of the rear building',
        '방통고협의실':'Open Secondary Schools a consultation room',
        '방송통신고 교무실':"Open Secondary Schools Teachers' Office",
        '영어교실':'English room',
        '국어교실':'Korean room',
        '후관 3층 화장실':'a restroom on the 3rd floor of the rear building',
        '후관 3층 우측계단':'the right staircase on the 3rd floor of the rear building',
        '후관 4층 좌측 계단':'the left staircase on the 4th floor of the rear building',
        '사회교실1':'social room 1',
        '수학교실1':'math room 1',
        '수학교실2':'math room 2',
        '후관 4층 화장실':'a restroom on the 4th floor of the rear building',
        '후관 4층 우측 계단':'the right staircase on the 4th floor of the rear building',
        '세종관 입구':'Entrance of Sejong Building',
        '세종관 1층 중앙':'The center of the 1st floor of Sejong Building',
        '진로진학상담부':'Career counseling department',
        '세종관 1층 화장실':'1st floor restroom of Sejong Building',
        '인문사회부':'Department of Humanities and Social Affairs',
        '도서관':'Library of Ruina',
        '세종관 1층 계단':'1st floor stairs of Sejong Building',
        '세종관 2층 계단':'2nd floor stairs of Sejong Building',
        '2학년 야자실':'A self-study room for 2nd Graders',
        '세종관 3층 계단':'3st floor stairs of Sejong Building',
        '1학년 야자실':'A self-study room for 1st Graders',
        '매점':'store',
        '경비실':'A security office',
        '창학관 - 세종관 이음길':'Changhak Building - Road to Sejong Building',
        '계림동산':'Gyelim-dongsan',
        '급식실':"cafeteria",
        '음악당':"music room",
        '음악당 화장실':"music room restroom",
        '체육관 입구':"the entrance to the Gym",
        '체육관':"Gym"
    };

export default EnglishKeys;